/**
 * Generates the API's copy of the legal documents from the app's.
 *
 * The app bundles them because it must work before sign-in and offline, and
 * the website needs the same text because the app stores require a privacy
 * policy at a public URL. Two hand-maintained copies of a privacy policy
 * drift, and the half that drifts is the half nobody is reading — which in
 * this project has already happened once, to a wordmark, on three screens.
 *
 * So there is one source, constants/legal.ts, and this generates the other at
 * build time. Editing the generated file is pointless; the next build wins.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', '..', 'constants', 'legal.ts');
const target = join(here, '..', 'src', 'legalText.generated.ts');

const src = readFileSync(source, 'utf8');

/**
 * Evaluated rather than parsed.
 *
 * The file is a plain array of string literals with two interpolations, so
 * evaluating the literal with those two in scope is exact where a regex over
 * multi-line template strings would be a guess.
 */
const decl = src.indexOf('export const LEGAL');
if (decl < 0) throw new Error('sync-legal: no LEGAL export in ' + source);

const start = src.indexOf('= [', decl) + 2;
const literal = src.slice(start, src.lastIndexOf('];') + 1);

const FEE_PERCENT = '10%';
const formatNaira = (n) => Number(n).toLocaleString('en-NG');
const LEGAL = eval('(' + literal + ')');

if (!Array.isArray(LEGAL) || LEGAL.length === 0) {
  throw new Error('sync-legal: parsed no documents');
}
for (const doc of LEGAL) {
  if (!doc.title || !Array.isArray(doc.body) || doc.body.length === 0) {
    throw new Error('sync-legal: a document has no title or no body');
  }
}

writeFileSync(
  target,
  '/* Generated by scripts/sync-legal.mjs from constants/legal.ts. Do not edit. */\n' +
    'export const LEGAL: { title: string; body: string[] }[] =\n' +
    JSON.stringify(LEGAL, null, 2) +
    ';\n',
);

console.log(
  'sync-legal: ' + LEGAL.length + ' documents (' +
    LEGAL.map((d) => d.title + ' ' + d.body.length).join(', ') + ')',
);
